### ISSUE TITLE
doc_paging error

### ISSUE THREAD

**Issue by jackkcaj2000** [bwdbooks/nodejs-mongodb-angularjs-web-development#1]
Ch15 : doc_paging.js
I thought that placing the pagination within a recursive call would be a good idea as well but the recursion occurs quicker than mongodb can query the database.  So on my machine the database is closed before each 'page' is printed.

What would be a good workaround for this?

**Comment by bwdbooks** [comment]
For the example script you could use a JavaScript timer to delay closing the database. In a real world example such as a server-side script handling a web requests the application doesn't end until the server shuts down and therefore the connection to the database can be left open. If you do not want the connection to remain open then you can use another mechanism such as the events described in chapter 4 to close the connection once you have finished processing the database requests.
